name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write # Ajuste para upload do SARIF 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Seteup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  
  testes:
    needs: [build]
    uses: diego64/desafio-cicd/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Analise do Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Review-Filmes.Web/Dockerfile

      - name: Efetuando login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build e Puh da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: src/Review-Filmes.Web/Dockerfile
          tags: |
            diego64/desafio-cicd:latest
            diego64/desafio-cicd:v${{ github.run_number }}

      - name: Execução do Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'image'
          image-ref: diego64/desafio-cicd:v${{ github.run_number }}
          format: sarif
          output: trivy-docker-result.sarif
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload do arquivo trivy para o repositório
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: trivy-docker-result.sarif